# Generated by Django 4.2.19 on 2026-02-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rice_web", "0004_humanassistantrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="humanassistantrequest",
            name="admin_remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="humanassistantrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
